### ISSUE TITLE
Doesn't start at all.

### ISSUE THREAD

**Issue by qamwxy** [xKiian/Richup.io-Raider#1]
Python: 3.12.4
Can't find which python do I use, also no requirements list provided.

**Comment by qamwxy** [comment]
nvm fonud the requirement but still, 

```
Traceback (most recent call last):
  File "C:\Users\%USER%\Downloads\Richup.io-Raider-main\main.py", line 63, in <module>
    main()
  File "C:\Users\%USER%\Downloads\Richup.io-Raider-main\main.py", line 60, in main
    while True: threading.Thread(target=spam().join).start()
                                        ^^^^^^
  File "C:\Users\%USER%\Downloads\Richup.io-Raider-main\main.py", line 18, in __init__
    self.ws     = websocket.WebSocket()
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
[+] Success: 0 Failed: 0
```

which python version do i use?

**Comment by xKiian** [comment]
You need to use websocket-client instead of websocket

```
pip uninstall websocket
pip install websocket-client
```

but i think it's patched now anyway 🤷

**Comment by qamwxy** [comment]
It started, but
> but i think it's patched now anyway 🤷
It is. Still, thank you for help, maybe in the future I will try to fix it somehow.

**Comment by xKiian** [comment]
so i just tested it and it still works fine

**Comment by qamwxy** [comment]
hm, it showed successful for me, but didn't actually do anything

**Comment by xKiian** [comment]
did you enter the game code correctly?

**Comment by qamwxy** [comment]
Yeah, tried w a link and just the code
